@service-url = http://localhost:4004
@odatav2 = {{service-url}}/v2/odata/MyService


#### ------------------------------------------------------------------------
# POST create BOOK
# HTTP/1.1 201 Created
### -----------------------------------------------------------------------
POST {{odatav2}}/Books
Content-Type: application/json

{
    "title": "BK1",
    "descr": "BK2222",
    "author_ID": 101,
    "genre_ID": 11,
    "stock": 12,
    "price": "11.11",
    "currency_code": "GBP"
}